functions/models/promise.js

feat(promise): updater schema, status now accepts 'At Risk'

---

functions/api/promiseUpdate.js
functions/api/promises.js
functions/index.js
functions/models/promiseUpdate.js
functions/schemas/promiseUpdate.js

feat(promiseUpdate): setup

---

functions/api/politicians.ts

Require auth for the /politicians CRUD endpoints

---

functions/package-lock.json
functions/package.json
functions/schemas/list.ts
functions/test/sample.test.ts
functions/test/schemas/list.test.ts
functions/types.d.ts

Issue ref. [phefbRpN](https://trello.com/c/phefbRpN/367-plan-list-feature)
The large size is because of `package-json.lock`. :)
This PR:
- implements the primitive fields for the List schema and validations for them
- sets up the testing framework, tests the List schema
Further associations with the Promises schema will be done in a separate PR.

Create a basic List schema

---

functions/api/lists.ts
functions/etc/middlewares.ts

feat: create list endpoints (stubs)

---

functions/models/list/add.ts
functions/test/models/list/add.test.ts

feat: implement List#add

---

functions/models/list/get.ts
functions/test/models/list/get.test.ts

feat: implement List#get

---

functions/models/list/list.ts
functions/test/models/list/list.test.ts

feat: implement List#list

---

functions/models/list.ts

Depends on PRs #74 #75 #76 
Enables the public interface for the client code to import in their modules.

feat: set up public interface for the List model

---

functions/api/lists.ts
functions/api/lists/get.ts

Depends on PR #77 
I wrote some tests for it locally, I believe it should be ok. If it's not, you know where to find me. :)

feat: implement the getList endpoint

---

functions/api/lists.ts
functions/api/lists/list.ts

Depends on PR #77 
I wrote some tests for it locally, I believe it should be ok. If it's not, you know where to find me. :)

feat: implement the getAllLists endpoint

---

.gitignore
functions/api/lists.ts
functions/schemas/list.ts
functions/schemas/promise.ts
functions/test/env.test.ts

ERROR: api/lists.ts[9, 1]: Import sources within a group must be alphabetized.
ERROR: api/lists.ts[33, 10]: Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like `() => void`.
ERROR: schemas/list.ts[5, 16]: Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.
ERROR: schemas/list.ts[12, 3]: The key 'promise_ids' is not sorted alphabetically
ERROR: schemas/list.ts[28, 3]: The key 'promise_ids' is not sorted alphabetically
ERROR: schemas/promise.ts[57, 13]: Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.
ERROR: schemas/promise.ts[108, 3]: The key 'list_ids' is not sorted alphabetically
ERROR: schemas/promise.ts[127, 3]: The key 'list_ids' is not sorted alphabetically
ERROR: …

fix: typescript errors

---

functions/index.ts

this will tell firebase to deploy the lists api endpoints

feat: include lists in functions

---

functions/api/lists.ts
functions/api/lists/create.ts

from this PR I agree even more that validation should be done in the model rather than in the route handler

feat: route handler for create list

---

functions/schemas/list.ts

add to schema:
* contributor_id
* live

feat(List): update schema

---

functions/models/promise.ts

I believe implementation should conform to what we previously discussed:
- on `Promise.create`, the promise to be created accepts, among others, the `list_ids` field.
- we fetch every `list_id` from the `list_ids` field, fetch the list and update its `promise_ids` array with our newly created promise.
P.S. I actually had this covered with tests, but unfortunately could not submit those - due to TSC errors and Firebase being instantiated directly in the module scopes, making it impossible to mock Firebase.
I have resolved these issues locally, wrote the tests, ran them, we are in the green. But I could, of course, have missed something, or made a mistake copying the solution code back in.

feat: update promise_id in lists on Promise.add

---

.gitignore
functions/scripts/batch-write.ts

prior to this there was a `functions/scripts/index.ts` that was a (dangerous) utility function for batch updating a collection
I have just used it to update a List to contain all IDs of promises that had source_url matching the manifesto URL of Pakatan Harapan
317 were updated
this batch-write.ts has been made generic after that task was done
this PR is open for suggestion on how it can be improved for further use although hopefully we won't need it again/as often

feat(scripts/batch-write): update batch write script

---

functions/package.json
functions/scripts/batch-read.ts
functions/scripts/batch-write.ts
functions/scripts/db.ts

- also: create db.ts so that db cant just be imported
- formalise step of using batch-read to get list, then batch-write to operate on that filtered list

feat(scripts): create batch-read + update batch-write

---

functions/etc/utils/detectArrayChanges.ts
functions/etc/utils/parseQueryForRef.ts
functions/models/list/list.ts
functions/schemas/promise.ts
functions/test/models/list/add.test.ts
functions/test/models/list/get.test.ts

Ref. [8QeAeEUk](https://trello.com/c/8QeAeEUk/254-api-address-ts-warnings)
There were some type errors which I resolved (i.e. "hacked around") with the `any` type identifier. We may want to go back, identify and specify the correct type later.

fix: resolve errors preventing specs from running

---

functions/package-lock.json
functions/package.json
functions/test/models/list/add.test.ts
functions/test/models/list/get.test.ts
functions/test/models/list/list.test.ts
functions/test/support/factories/list.ts

https://github.com/OpenPromisesProject/op-serverless-api/issues/105
This PR currently creates a factory for the List model only, in order to serve as a proof of concept.

chore: use factories in tests

---

functions/package-lock.json
functions/package.json

https://github.com/OpenPromisesProject/op-serverless-api/issues/103

chore: update outdated packages

---

functions/models/contributor.ts
functions/models/politician.ts
functions/models/promise/index.ts
functions/models/promiseUpdate.ts
functions/package-lock.json
functions/schemas/contributor.ts
functions/schemas/politician.ts
functions/schemas/promiseUpdate.ts
functions/scripts/batch-read.ts
functions/scripts/batch-write.ts

fix: update imported file name

---

functions/models/lead/add.ts
functions/models/lead/index.ts
functions/test/models/lead/add.test.ts
functions/test/models/lead/types.d.ts

Depends on  PR Ref. #108
Ref. FN2s10GL

feat: implement LeadModel.add

---

functions/package.json

also I have updated firebase deployment so we are on node v10 there now

add node 10 engine into package.json

---

functions/api/lists.ts
functions/api/lists/listAll.ts
functions/api/lists/listLive.ts
functions/models/list/list.ts
functions/package-lock.json
functions/package.json

feat: setup list all lists for admin

---

functions/etc/utils/index.ts
functions/models/promise/index.ts
functions/models/promise/list.ts
functions/models/promise/update.ts
functions/models/promiseUpdate.ts
functions/schemas/promise.ts
functions/scripts/batch-read.ts
functions/scripts/batch-write.ts
functions/scripts/db.ts
functions/scripts/types.ts
functions/tsconfig.json

fix some ts errors

---

functions/models/promiseUpdate.ts
functions/scripts/batch-read.ts
functions/scripts/batch-write.ts

reordering of imports based on alphabetised order

ran yarn lint --fix

---

README.md

https://github.com/OpenPromisesProject/op-serverless-api/issues/142
Based on the PR: https://github.com/OpenPromisesProject/op-serverless-api/pull/143

chore: update the readme file

---

functions/index.ts
functions/models/contributor.ts
functions/models/list/index.ts
functions/models/politician.ts
functions/models/promise/index.ts
functions/models/promiseUpdate.ts
functions/package-lock.json
functions/package.json
functions/services/db.ts

- removes error complaining about app being initialized more than once

refactor(models): create db service

---

functions/models/contributor.ts
functions/models/politician.ts
functions/models/promiseUpdate.ts
functions/schemas/politician.ts
functions/services/db.ts

to accommodate new fields: constituency, administration_name, party

Feat(schemas): update politician schema

---

functions/models/promise/index.ts
functions/models/promise/list.ts
functions/models/promise/update.ts
functions/package-lock.json
functions/package.json
functions/services/db.ts

fix: reduce ts errors from 62 to 39

---

functions/etc/utils/index.ts
functions/models/politician.ts
functions/models/promise/get.ts
functions/models/promise/list.ts
functions/models/types.ts

fix: reduce TS errors from 39 to 30

---

functions/api/promiseUpdate.ts
functions/api/promises.ts
functions/etc/utils/index.ts
functions/models/contributor.ts
functions/models/list/list.ts
functions/models/politician.ts
functions/schemas/contributor.ts

fix: reduce typescript errors from 30 to 18

---

functions/api/promiseUpdate.ts
functions/api/promises.ts
functions/etc/middlewares.ts
functions/models/contributor.ts
functions/models/promiseUpdate.ts

fix: reduced typescript errors down to 0

---

functions/models/contributor.ts
functions/models/politician.ts
functions/models/promise/index.ts
functions/models/promise/update.ts
functions/models/promiseUpdate.ts

fix: model should not handle controller logic
